"""update

Revision ID: a30a2603d736
Revises: 7bea9c9a619b
Create Date: 2025-06-23 15:08:07.331632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30a2603d736'
down_revision: Union[str, None] = '7bea9c9a619b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'isgdevice', ['ip_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'isgdevice', type_='unique')
    # ### end Alembic commands ###
